In [27]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from imblearn.over_sampling import SMOTE
from sklearn.feature_selection import SelectKBest, f_classif

In [28]:
data = pd.read_csv('Data/SyriaTel_Customer_Churn.csv')

data.head()

,state,account length,area code,phone number,international plan,voice mail plan,number vmail messages,total day minutes,total day calls,total day charge,...,total eve calls,total eve charge,total night minutes,total night calls,total night charge,total intl minutes,total intl calls,total intl charge,customer service calls,churn
0,KS,128,415,382-4657,no,yes,25,265.1,110,45.07,...,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,OH,107,415,371-7191,no,yes,26,161.6,123,27.47,...,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,NJ,137,415,358-1921,no,no,0,243.4,114,41.38,...,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
3,OH,84,408,375-9999,yes,no,0,299.4,71,50.90,...,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
4,OK,75,415,330-6626,yes,no,0,166.7,113,28.34,...,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False

In [29]:
# Encode categorical variables

# Encode the 'state' categorical column using one-hot encoding
encoder = OneHotEncoder(drop='first')  # Drop first category to avoid multicollinearity
state_encoded = pd.DataFrame(encoder.fit_transform(data[['state']]))  # Encode 'state' column

# Drop the original 'state' column from the dataset
data = data.drop(columns=['state'])

# Concatenate the encoded 'state' columns with the original dataset
data = pd.concat([data, state_encoded], axis=1)

# Encode other categorical variables
encoder = LabelEncoder()
data['international plan'] = encoder.fit_transform(data['international plan'])
data['voice mail plan'] = encoder.fit_transform(data['voice mail plan'])

# Split features and target variable
X = data.drop(columns=['churn'])
y = data['churn']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)